"""
QMIX Monotonic Mixing Network (Section 3 from the paper).

Combines individual agent Q-values into Q_tot with monotonicity constraint:
  ∂Q_tot / ∂Q_i >= 0,  ∀i ∈ N

The mixing network's weights are generated by hypernetworks conditioned
on the global state s_t, ensuring non-negative weights.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class HyperNetwork(nn.Module):
    """Hypernetwork that generates mixing weights from global state.

    Outputs are passed through abs() to ensure non-negativity (monotonicity).
    """

    def __init__(self, state_dim: int, n_agents: int, hidden_dim: int, output_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(state_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )
        self.n_agents = n_agents

    def forward(self, state: torch.Tensor) -> torch.Tensor:
        return self.net(state)


class QMIXMixingNetwork(nn.Module):
    """QMIX mixing network with monotonicity constraint.

    Architecture:
      - Two hypernetworks generate weights W1, W2 from global state
      - Weights passed through abs() for monotonicity
      - Two hypernetworks generate biases b1, b2
      - Q_tot = W2 * ELU(W1 * Q_agents + b1) + b2

    This ensures ∂Q_tot/∂Q_i ≥ 0 for all agents i.
    """

    def __init__(
        self,
        n_agents: int,
        state_dim: int,
        mixing_hidden_dim: int = 64,
        hyper_hidden_dim: int = 64,
    ):
        super().__init__()
        self.n_agents = n_agents
        self.state_dim = state_dim
        self.mixing_hidden_dim = mixing_hidden_dim

        self.hyper_w1 = HyperNetwork(
            state_dim, n_agents, hyper_hidden_dim, n_agents * mixing_hidden_dim
        )
        self.hyper_b1 = nn.Sequential(
            nn.Linear(state_dim, mixing_hidden_dim),
        )

        self.hyper_w2 = HyperNetwork(
            state_dim, n_agents, hyper_hidden_dim, mixing_hidden_dim
        )
        self.hyper_b2 = nn.Sequential(
            nn.Linear(state_dim, hyper_hidden_dim),
            nn.ReLU(),
            nn.Linear(hyper_hidden_dim, 1),
        )

    def forward(
        self,
        agent_q_values: torch.Tensor,
        global_state: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            agent_q_values: (batch, n_agents) individual Q-values Q_i
            global_state: (batch, state_dim) global state s_t
        Returns:
            q_total: (batch, 1) mixed Q_tot
        """
        batch_size = agent_q_values.size(0)
        q_vals = agent_q_values.view(batch_size, 1, self.n_agents)

        # First layer: abs() ensures monotonicity
        w1 = torch.abs(self.hyper_w1(global_state))
        w1 = w1.view(batch_size, self.n_agents, self.mixing_hidden_dim)
        b1 = self.hyper_b1(global_state).view(batch_size, 1, self.mixing_hidden_dim)
        hidden = F.elu(torch.bmm(q_vals, w1) + b1)

        # Second layer
        w2 = torch.abs(self.hyper_w2(global_state))
        w2 = w2.view(batch_size, self.mixing_hidden_dim, 1)
        b2 = self.hyper_b2(global_state).view(batch_size, 1, 1)
        q_total = torch.bmm(hidden, w2) + b2

        return q_total.squeeze(-1).squeeze(-1)  # (batch,)
